### ISSUE TITLE
Unknown error while trying to install package with 1 as return value

### ISSUE THREAD

**Issue by DerickGamer** [jshttp/http-errors#89]
# The error
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your 
dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\*\\Desktop\\Derick\\Programming Tutorial App\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.1.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:203:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:203:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Program Files\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Program Files\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];      
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:387:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:449:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:715:12)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\*\\Desktop\\Derick\\Programming Tutorial App\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\*\Desktop\Derick\Programming Tutorial App\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.1.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*\AppData\Local\npm-cache\_logs\2022-05-15T16_16_43_556Z-debug-0.log

This error happens with the latest version of `npm` (8.10) at Windows 10.
Sorry for the random code-formatting on the errors, but I want to send the whole promp, so I can't remove them :P
And the spaces, hmm...

**Comment by DerickGamer** [comment]
Nvm, it is just random italicitations. And no space problem, I guess

**Comment by DerickGamer** [comment]
After further investigation, I realized that it is an error with a sass library, not this package. Sorry for any intrusion (whatever it is)

**Comment by DerickGamer** [comment]
And sorry for my bad english :P
